---
- hosts: node
  become: yes
  become_user: root
  tasks:
    - name: Installs nginx web server
      apt: pkg=nginx state=present update_cache=true
      notify:
        - start nginx
  handlers:
    - name: start nginx
      service: name=nginx state=restarted
